require 'fileutils'
require 'pty'
require 'open-uri'
require 'mustache'
require 'thor'
require 'traveler/util'

module Traveler
  extend Util

  BUCKET_ROOT = 'https://traveling-ruby.s3-us-west-2.amazonaws.com/'.freeze
  RELEASES_URL = 'https://github.com/YOU54F/traveling-ruby/releases/download/'.freeze

  PWD = Dir.pwd.freeze
  SKEL_PATH = File.expand_path('../../skel', __FILE__).freeze

  CONFIGFILE = 'Travelfile'.freeze
  CONFIGFILE_PATH = File.join(PWD, CONFIGFILE).freeze
  CONFIGFILE_SKEL = skeldir(CONFIGFILE).freeze

  GEMFILE = 'Gemfile'.freeze
  GEMFILE_PATH = File.join(PWD, GEMFILE)
  GEMFILE_SKEL = skeldir(GEMFILE)

  RUBY_VERSIONS = %w[
    2.6.10
    3.0.6
    3.1.4
    3.2.3
    3.3.0
  ].freeze

  TRAVELING_RUBY_VERSIONS = %w[
    20230803
    20230605
    20230601
    20230508
    20240215
  ].freeze

  PLATFORMS = %w[
    linux-x86_64
    linux-arm64
    osx-x86_64
    osx-arm64
  ].freeze

  OPTED_PLATFORMS = []
  WRAPPERS = {}

  SIGNATURE = <<-STR.unindent.strip.freeze
  # ================================================================= #
  # Autogenerated by Traveler. Any updates will be lost on next build #
  # ================================================================= #
  STR

  SUCCESS_ICONS = %w[
    10004   128515  128516  128522
    128523  128540  127866  128079
    128076  128077  128175  128176
    127853  127942  128640  127919
  ].map {|c| [c.to_i].pack('U*')}.freeze
end
